name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: GitHub Action for Build
      uses: buildtool/build-action@v1
      with:
        # specify Dockerfile to use
        dockerfile: python/Dockerfile
